/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard, Andrew Yang, Matthew Jasper
-/
import FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Abstract -- abstract Hecke ops
import FLT.AutomorphicForm.QuaternionAlgebra.Defs -- definitions of automorphic forms
import FLT.QuaternionAlgebra.NumberField -- rigidifications of quat algs
import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex
import Mathlib.RingTheory.DedekindDomain.FiniteAdeleRing
import FLT.DedekindDomain.FiniteAdeleRing.LocalUnits -- for (π 0; 0 1)
import FLT.Mathlib.Topology.Algebra.RestrictedProduct
/-

# Concrete Hecke operators

Hecke operators for spaces of automorphic forms on totally definite quaternion algebras
of level `U₁(S)`, where `S` is a finite set of finite places of the totally real number
field `F`, and `U₁(S)` is the matrices which are of the form `(a *;0 a)` mod `v` for
all `v ∈ S`.

## Main definitions

All in the `TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm` namespace.

Let `r : Rigidification F D` be an `𝔸_F^∞`-algebra isomorphism `D ⊗[F] 𝔸_F^∞ = M₂(𝔸_F^∞)`,
needed to interpret the local factors `Dᵥ` as matrix rings so we can define Hecke operators
as matrices.

* `HeckeOperator.T r R v` -- the Hecke operator `Tᵥ` associated to `(ϖᵥ 0; 0 1)` at a (good)
  place `v` (via the rigidification `r`), as an `R`-linear endomorphism of
  `WeightTwoAutomorphicFormOfLevel (U1 r S) R`.
* `HeckeOperator.U r S R a ha` -- the Hecke operator `Uᵥ,ₐ` associated to `(a 0;0 1)` at
  a (bad) place `v`; here `a : v.adicCompletionIntegers F` and `ha` is a proof that `a ≠ 0`,
  as an `R`-linear endomorphism of `WeightTwoAutomorphicFormOfLevel (U1 r S) R`.
* `HeckeAlgebra F D r S R` -- the Hecke algebra generated by the `Tᵥ` and `Uᵥ,ₐ`. Built
  as a type, coerced from a subalgebra of the endomorphism algebra of the forms.
* `HeckeAlgebra.T D r R v hv` -- `Tᵥ` as a term of type `HeckeAlgebra F D r S R`
* `HeckeAlgebra.U D r R v hv a ha` -- `Uᵥ,ₐ` as a term of type `HeckeAlgebra F D r S R`

-/

/-

## A finiteness result

The existence of abstract Hecke operators relies on a certain double coset space being
a finite union of single cosets. In our situation we can supply this finiteness proof
via a topological argument, which we abstract here.

-/

section finiteness

open Topology Set

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    {g : G} {U V : Subgroup G}

open scoped Pointwise in
lemma QuotientGroup.mk_image_finite_of_compact_of_open (hU : IsCompact (U : Set G))
    (hV : IsCompact (V : Set G)) (hVopen : IsOpen (V : Set G)) :
    (QuotientGroup.mk '' (U * g • V) : Set (G ⧸ V)).Finite := by
  have : DiscreteTopology (G ⧸ V) := by
    rw [← forall_open_iff_discrete]
    intro s
    rw [← (isQuotientMap_mk V).isOpen_preimage, ← (QuotientGroup.mk_surjective).image_preimage s,
      preimage_image_mk_eq_iUnion_image, iUnion_subtype]
    conv in ⋃ x ∈ _, _ => change ⋃ x ∈ (V : Set G), _
    rw [iUnion_mul_right_image]
    exact IsOpen.mul_left hVopen
  exact ((hU.mul <| hV.image (by fun_prop)).image continuous_mk).finite_of_discrete

end finiteness


open NumberField IsQuaternionAlgebra.NumberField IsDedekindDomain

-- let F be a totally real number field
variable (F : Type*) [Field F] [NumberField F] [IsTotallyReal F]

-- Let D/F be a quaternion algebra
variable (D : Type*) [Ring D] [Algebra F D] [IsQuaternionAlgebra F D]

-- Let r be a rigidification of D, which is a collection of isomorphisms D ⊗ Fᵥ = M₂(Fᵥ)
-- for all finite places v of F, compatible with the adelic structure (i.e. inducing
-- an isomorphism D ⊗_F 𝔸_F^f = M₂(𝔸_F^f))
variable (r : Rigidification F D)

-- Let S be a finite set of finite places of F (the level)
variable (S : Finset (HeightOneSpectrum (𝓞 F)))

-- let P be a good prime
variable {P : HeightOneSpectrum (𝓞 F)} (hP : P ∉ S)

open TotallyDefiniteQuaternionAlgebra
-- let's do T_P : S_2^D(U_1(S)) -> S_2^D(U_1(S))
namespace TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm

open IsDedekindDomain.HeightOneSpectrum

open scoped TensorProduct

variable {F D} in
open scoped TensorProduct.RightActions in
/-- U1(S) -/
noncomputable abbrev U1 : Subgroup (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ :=
  Subgroup.map (Units.map r.symm.toMonoidHom) (GL2.TameLevel S)

variable {F D} in
open scoped TensorProduct.RightActions in
lemma U1_compact : IsCompact (U1 r S : Set (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ) :=
  sorry -- #583, long

variable {F D} in
open scoped TensorProduct.RightActions in
lemma U1_open : IsOpen (U1 r S : Set (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ) :=
  sorry -- #583, long

variable (R : Type*) [CommRing R]

namespace HeckeOperator

variable {F D S} in
set_option maxSynthPendingDepth 1 in
open scoped TensorProduct.RightActions in
/-- The Hecke operator T_v as an R-linear map from R-valued quaternionic weight 2
automorphic forms of level U_1(S).
-/
noncomputable def T (v : HeightOneSpectrum (𝓞 F)) :
    WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
    WeightTwoAutomorphicFormOfLevel (U1 r S) R :=
  letI : DecidableEq (HeightOneSpectrum (𝓞 F)) := Classical.typeDecidableEq _
  let g : (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ :=
    Units.map r.symm.toMonoidHom (Matrix.GeneralLinearGroup.diagonal
    ![FiniteAdeleRing.localUniformiserUnit F v, 1])
  AbstractHeckeOperator.HeckeOperator (R := R) g (U1 r S) (U1 r S)
  (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r S) (U1_compact r S) (U1_open r S))

variable {F D} in
set_option maxSynthPendingDepth 1 in
open scoped TensorProduct.RightActions in
/-- The Hecke operator U_{v,α} associated to the matrix (α 0;0 1) at v,
considered as an R-linear map from R-valued quaternionic weight 2
automorphic forms of level U_1(S). Here α is a nonzero element of 𝓞ᵥ.
We do not demand the condition v ∈ S, the bad primes, but this operator
should only be used in this setting. See also `T r v` for the good primes.
-/
noncomputable def U {v : HeightOneSpectrum (𝓞 F)}
    (α : v.adicCompletionIntegers F) (hα : α ≠ 0) :
    WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
    WeightTwoAutomorphicFormOfLevel (U1 r S) R :=
  letI : DecidableEq (HeightOneSpectrum (𝓞 F)) := Classical.typeDecidableEq _
  let g : (D ⊗[F] (IsDedekindDomain.FiniteAdeleRing (𝓞 F) F))ˣ :=
    Units.map r.symm.toMonoidHom (Matrix.GeneralLinearGroup.diagonal
    ![FiniteAdeleRing.localUnit F ⟨(α : v.adicCompletion F),
    (α : v.adicCompletion F)⁻¹, by
      rw [mul_inv_cancel₀]
      exact_mod_cast hα, by
      rw [inv_mul_cancel₀]
      exact_mod_cast hα⟩, 1])
  AbstractHeckeOperator.HeckeOperator (R := R) g (U1 r S) (U1 r S)
  (QuotientGroup.mk_image_finite_of_compact_of_open (U1_compact r S) (U1_compact r S) (U1_open r S))

lemma _root_.Ne.mul {M₀ : Type*} [Mul M₀] [Zero M₀] [NoZeroDivisors M₀] {a b : M₀}
  (ha : a ≠ 0) (hb : b ≠ 0) : a * b ≠ 0 := mul_ne_zero ha hb

open scoped Pointwise

section CosetComputation
-- local F_v

-- set_option synthInstance.maxHeartbeats 0

variable (v : HeightOneSpectrum (𝓞 F))
variable (α : v.adicCompletionIntegers F)
variable (hα : α ≠ 0)

variable {F α hα} in
noncomputable def U1v : Subgroup (GL (Fin 2) (adicCompletion F v)) := (GL2.localTameLevel v)

variable {F v} in
noncomputable def g : (GL (Fin 2) (adicCompletion F v)) :=
  Matrix.GeneralLinearGroup.diagonal (![⟨(α : v.adicCompletion F),
    (α : v.adicCompletion F)⁻¹, by
      rw [mul_inv_cancel₀]
      exact_mod_cast hα, by
      rw [inv_mul_cancel₀]
      exact_mod_cast hα⟩, 1])

set_option synthInstance.maxHeartbeats 0 in
-- double coset space
variable {F v} in
noncomputable def doubleCosets :
  Set ((GL (Fin 2) (adicCompletion F v)) ⧸ ↑(U1v v)) :=
  (QuotientGroup.mk '' ((U1v v) * g α hα • ↑(U1v v) ))

variable {F v} in
noncomputable def gt (t : v.adicCompletionIntegers F) : (GL (Fin 2) (adicCompletion F v)) := by
  let gtInv : Invertible !![(α : v.adicCompletion F), t; 0, 1].det :=
  { invOf := (α : v.adicCompletion F)⁻¹,
    invOf_mul_self :=
      by simp only [Matrix.det_fin_two_of,
        mul_one, mul_zero, sub_zero]; rw [inv_mul_cancel₀]; exact_mod_cast hα,
    mul_invOf_self :=
      by simp only [Matrix.det_fin_two_of,
        mul_one, mul_zero, sub_zero]; rw [mul_inv_cancel₀]; exact_mod_cast hα }
  exact Matrix.unitOfDetInvertible !![(α : v.adicCompletion F), t; 0, 1]

variable {F v α hα} in
noncomputable def ht (t : v.adicCompletion F) : (GL (Fin 2) (adicCompletion F v)) := by
  let htInv : Invertible !![1, t; 0, 1].det :=
  { invOf := 1,
    invOf_mul_self :=
      by simp only [Matrix.det_fin_two_of, mul_one, mul_zero, sub_zero],
    mul_invOf_self :=
      by simp only [Matrix.det_fin_two_of, mul_one, mul_zero, sub_zero] }
  exact Matrix.unitOfDetInvertible !![1, t; 0, 1]

variable {F v} in
noncomputable def singleCosetsFunction
  (t : ↑(adicCompletionIntegers F v) ⧸ (AddSubgroup.map (AddMonoidHom.mulLeft α)
    (⊤ : AddSubgroup ↑(adicCompletionIntegers F v)))) :
  ((GL (Fin 2) (adicCompletion F v)) ⧸ ↑(U1v v)) := by
  let tLift : ↑(adicCompletionIntegers F v) := Quotient.out t
  exact QuotientGroup.mk (gt α hα tLift)

set_option maxHeartbeats 400000
-- explicit matrix coset computations
variable {F v} in
lemma U_coset : Set.BijOn (singleCosetsFunction α hα) ⊤ (doubleCosets α hα) := by
  have r (A : Matrix (Fin 2) (Fin 2) (adicCompletion F v)) [Invertible A.det] :
    (↑(A.unitOfDetInvertible) : Matrix (Fin 2) (Fin 2) (adicCompletion F v)) = A := rfl
  constructor
  · intro t h
    have m : (gt α hα (Quotient.out t)) =  ht ↑(Quotient.out t) * g α hα := by
        have r₁ : (g α hα : Matrix (Fin 2) (Fin 2) (adicCompletion F v))
          = !![↑α, 0; 0, 1] := by
          rw[g]
          ext i j
          rw[Matrix.GeneralLinearGroup.diagonal]
          fin_cases i
          · fin_cases j
            · simp
            simp
          fin_cases j
          · simp
          simp
        ext i j; push_cast
        rw[gt, ht, r₁]
        rw[r, r]
        rw[Matrix.mul_apply]
        simp only [Fin.sum_univ_two, Fin.isValue]
        fin_cases i
        · fin_cases j
          · simp
          simp
        simp
    rw[singleCosetsFunction, m, doubleCosets]
    use (ht ↑(Quotient.out t) * g α hα)
    constructor
    · use ht ↑(Quotient.out t)
      constructor
      · rw[ht]
        constructor
        · let htInt : ((Matrix (Fin 2) (Fin 2) ↥(adicCompletionIntegers F v))ˣ) := by
            let htInv : Invertible !![1, (Quotient.out t); 0, 1].det :=
            { invOf := 1,
              invOf_mul_self :=
              by simp only [Matrix.det_fin_two_of, mul_one, mul_zero, sub_zero],
              mul_invOf_self :=
              by simp only [Matrix.det_fin_two_of, mul_one, mul_zero, sub_zero] }
            exact Matrix.unitOfDetInvertible !![1, (Quotient.out t); 0, 1]
          use htInt
          refine Units.eq_iff.mp ?_
          rw[r]
          have ho : (htInt = !![1, (Quotient.out t); 0, 1]) := rfl
          rw[Units.coe_map, ho]
          simp only [RingHom.toMonoidHom_eq_coe, MonoidHom.coe_coe, RingHom.mapMatrix_apply,
            ValuationSubring.coe_subtype]
          ext i j
          fin_cases i
          · fin_cases j
            · simp
            simp
          fin_cases j
          · simp
          simp
        rw[r]
        simp
      use g α hα
      simp only [and_true]
      use (1 : GL (Fin 2) (adicCompletion F v))
      simp only [SetLike.mem_coe, smul_eq_mul, mul_one, and_true]
      exact Subgroup.one_mem (U1v v)
    rfl

  constructor
  · intro t₁ h₁ t₂ h₂ h
    rw[singleCosetsFunction, singleCosetsFunction] at h
    have h₀ := QuotientGroup.eq.mp h
    have m : (gt α hα (Quotient.out t₁))⁻¹ * gt α hα (Quotient.out t₂)
      = ht ((α : v.adicCompletion F)⁻¹ *
        (( - (Quotient.out t₁) + (Quotient.out t₂)) : adicCompletion F v )) := by
        apply inv_mul_eq_iff_eq_mul.mpr
        rw [gt, gt, ht]
        ext i j; push_cast
        rw[r, r, r]
        rw[Matrix.mul_apply]
        simp only [Fin.sum_univ_two, Fin.isValue]
        fin_cases i
        · fin_cases j
          · simp
          simp only [Fin.zero_eta, Fin.isValue, Fin.mk_one, Matrix.of_apply, Matrix.cons_val',
            Matrix.cons_val_one, Matrix.cons_val_fin_one, Matrix.cons_val_zero, mul_one]
          rw[← mul_assoc, mul_inv_cancel₀, one_mul]; ring
          have hα₁ := Subtype.coe_ne_coe.mpr hα; assumption
        simp
    rw[m] at h₀
    obtain ⟨ ⟨ x, y ⟩ , z ⟩ := h₀
    apply_fun (fun (A : (Matrix (Fin 2) (Fin 2) (adicCompletion F v))ˣ) ↦ A 0 1) at y
    rw[ht] at y
    simp only [RingHom.toMonoidHom_eq_coe, Fin.isValue, Units.coe_map, MonoidHom.coe_coe,
      RingHom.mapMatrix_apply, ValuationSubring.coe_subtype, Matrix.map_apply] at y
    have w : ((x 0 1) : adicCompletion F v) = (α : v.adicCompletion F)⁻¹ *
        (( - (Quotient.out t₁) + (Quotient.out t₂)) : adicCompletion F v ) := by
        rw[y]; rfl
    conv_lhs =>
      apply Eq.symm (QuotientAddGroup.out_eq' t₁)
    conv_rhs =>
      apply Eq.symm (QuotientAddGroup.out_eq' t₂)
    apply QuotientAddGroup.eq.mpr
    use (x 0 1)
    constructor
    · simp
    simp only [Fin.isValue, AddMonoidHom.coe_mulLeft]
    apply (Subtype.coe_inj).mp; push_cast
    rw[w, ← mul_assoc, mul_inv_cancel₀, one_mul]
    have hα₁ := Subtype.coe_ne_coe.mpr hα; assumption

  intro co h
  obtain ⟨ co₀, ⟨ ⟨ co₁, h₁, ⟨ l, ⟨ ⟨ co₂, ⟨ h₂, z ⟩ ⟩ , hl ⟩ ⟩ ⟩ , h₀ ⟩ ⟩ := h
  have hp : co₀ = co₁ * (g α hα) * co₂ := by
    rw[← hl, ← z]; simp only [smul_eq_mul]; rw[mul_assoc]
  obtain ⟨ ⟨ ⟨ val_x₁, inv_x₁, val_inv_x₁, inv_val_x₁ ⟩ , y ⟩ , z ⟩ := h₁
  let a : (adicCompletionIntegers F v) := (val_x₁ 0 0)
  let b : (adicCompletionIntegers F v) := (val_x₁ 0 1)
  let c : (adicCompletionIntegers F v) := (val_x₁ 1 0)
  let d : (adicCompletionIntegers F v) := (val_x₁ 1 1)
  have h11 : c * (inv_x₁ 0 1) + d * (inv_x₁ 1 1) = 1 := by calc
    _ = (val_x₁ 1 0) * (inv_x₁ 0 1) + (val_x₁ 1 1) * (inv_x₁ 1 1) := rfl
    _ = (val_x₁ * inv_x₁) 1 1 := by rw[Matrix.mul_apply]; simp
    _ = 1 := by rw[val_inv_x₁]; simp
  have valc : Valued.v (c : adicCompletion F v) < 1 := by
    have hc : c = (val_x₁ 1 0) := rfl
    rw[hc]
    apply_fun (fun (A : (Matrix (Fin 2) (Fin 2) (adicCompletion F v))ˣ) ↦ A 1 0) at y
    simp only [RingHom.toMonoidHom_eq_coe, Units.map_mk, MonoidHom.coe_coe, RingHom.mapMatrix_apply,
      ValuationSubring.coe_subtype, Fin.isValue, Matrix.map_apply] at y
    rw[y]
    apply z.right
  have maxc : c ∈ IsLocalRing.maximalIdeal (adicCompletionIntegers F v) := by
    apply (ValuationSubring.valuation_lt_one_iff (adicCompletionIntegers F v) c).mpr
    have valc₁ : Valued.v.IsEquiv (adicCompletionIntegers F v).valuation := by
      apply Valuation.isEquiv_valuation_valuationSubring
    apply (Valuation.isEquiv_iff_val_lt_one.mp valc₁).mp
    exact valc
  have maxd : d ∉ IsLocalRing.maximalIdeal (adicCompletionIntegers F v) := by
    by_contra maxd₁
    have max1 : c * (inv_x₁ 0 1) + d * (inv_x₁ 1 1)
      ∈ IsLocalRing.maximalIdeal (adicCompletionIntegers F v) := by
      apply Ideal.add_mem
      repeat
        apply Ideal.mul_mem_right
        assumption
    rw[h11] at max1
    have nonunit : 1 ∈ nonunits ↥(adicCompletionIntegers F v) :=
      (IsLocalRing.mem_maximalIdeal 1).mp max1
    exact one_notMem_nonunits nonunit
  have dunit : IsUnit d := by
    by_contra dnotunit
    have dnonunit : d ∈ nonunits ↥(adicCompletionIntegers F v) := mem_nonunits_iff.mpr dnotunit
    have dmax : d ∈ IsLocalRing.maximalIdeal (adicCompletionIntegers F v) :=
      (IsLocalRing.mem_maximalIdeal d).mpr dnonunit
    exact maxd dmax
  obtain ⟨ dinv, dvalinv, dinvval ⟩ := isUnit_iff_exists.mp dunit

  let t : ↥(adicCompletionIntegers F v) ⧸ AddSubgroup.map (AddMonoidHom.mulLeft α) ⊤ := b * dinv
  use t
  simp only [Set.top_eq_univ, Set.mem_univ, true_and]
  rw[singleCosetsFunction, ← h₀]
  apply QuotientGroup.eq.mpr
  rw[hp, ← mul_assoc]
  have uele (u₁ : GL (Fin 2) (adicCompletion F v)) (hu₁ : u₁ ∈ U1v v)
    (u₂ : GL (Fin 2) (adicCompletion F v)) (hu₂ : u₂ ∈ U1v v) :
    u₁ * u₂ ∈ U1v v := by
    exact (Subgroup.mul_mem_cancel_right (U1v v) hu₂).mpr hu₁
  have ht : t = b * dinv := rfl
  rw[← QuotientAddGroup.out_eq' t] at ht
  have ht₁ := QuotientAddGroup.eq.mp ht
  obtain ⟨q, hq⟩ := ht₁
  simp only [AddSubgroup.coe_top, Set.mem_univ, AddMonoidHom.coe_mulLeft, true_and] at hq
  have hq₁ : Quotient.out t = b * dinv - α * q := by rw[hq]; ring
  apply uele
  · let muMatrix : Matrix (Fin 2) (Fin 2) (adicCompletion F v) :=
      !![a-(Quotient.out t)*c, (α : adicCompletion F v)⁻¹ * (b-(Quotient.out t)*d); c*α, d]
    let mup : GL (Fin 2) (adicCompletion F v) := (gt α hα (Quotient.out t))⁻¹ * (co₁ * g α hα)
    have hmup : mup = (gt α hα (Quotient.out t))⁻¹ * (co₁ * g α hα) := rfl
    have m : mup = muMatrix := by
      have hp1 : (gt α hα (Quotient.out t))⁻¹
        = !![(α : adicCompletion F v)⁻¹, -(α : adicCompletion F v)⁻¹*(Quotient.out t);0,1] := by
        rw[gt]
        push_cast; rw[r]
        rw[Matrix.inv_def]
        simp only [Matrix.det_fin_two_of, mul_one, mul_zero, sub_zero, Ring.inverse_eq_inv',
          Matrix.adjugate_fin_two_of, neg_zero, Matrix.smul_of, Matrix.smul_cons, smul_eq_mul,
          mul_neg, Matrix.smul_empty, neg_mul, EmbeddingLike.apply_eq_iff_eq]
        rw [inv_mul_cancel₀]; exact_mod_cast hα
      have hp2 : co₁ = !![(a : adicCompletion F v),b;c,d] := by
        rw[← y]
        ext i j
        simp only [RingHom.toMonoidHom_eq_coe, Units.map_mk, MonoidHom.coe_coe,
          RingHom.mapMatrix_apply, ValuationSubring.coe_subtype, Matrix.map_apply, Matrix.of_apply,
          Matrix.cons_val', Matrix.cons_val_fin_one]
        fin_cases i
        · fin_cases j
          · simp; rfl
          simp; rfl
        fin_cases j
        · simp; rfl
        simp; rfl
      have hp3 : g α hα = !![(α : adicCompletion F v), 0;0,1] := by
        rw[g]
        ext i j
        simp only [Matrix.of_apply, Matrix.cons_val', Matrix.cons_val_fin_one]
        fin_cases i
        · fin_cases j
          · simp; rfl
          simp; rfl
        fin_cases j
        · simp; rfl
        simp; rfl
      rw[hmup]; push_cast; rw[hp2, hp3]
      norm_cast; rw[hp1]
      unfold muMatrix
      simp only [neg_mul, Matrix.cons_mul, Nat.succ_eq_add_one, Nat.reduceAdd, Matrix.vecMul_cons,
        Matrix.head_cons, Matrix.smul_cons, smul_eq_mul, mul_zero, Matrix.smul_empty,
        Matrix.tail_cons, mul_one, Matrix.empty_vecMul, add_zero, Matrix.add_cons, zero_add,
        Matrix.empty_add_empty, Matrix.empty_mul, Equiv.symm_apply_apply, neg_smul, Matrix.neg_cons,
        Matrix.neg_empty, zero_smul, one_smul, EmbeddingLike.apply_eq_iff_eq]
      ring_nf
      ext i j
      fin_cases i
      · fin_cases j
        · simp only [Nat.succ_eq_add_one, Nat.reduceAdd, Fin.zero_eta, Fin.isValue,
          Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_fin_one]
          rw [mul_inv_cancel₀]
          · simp
          exact_mod_cast hα
        simp
      fin_cases j
      · simp
      simp

    rw[← hmup]

    let muMatrixInt : Matrix (Fin 2) (Fin 2) (adicCompletionIntegers F v) :=
      !![a-(Quotient.out t)*c, q*d; c*α, d]
    have inteq : (RingHom.mapMatrix ((v.adicCompletionIntegers F).subtype)).toMonoidHom
      muMatrixInt = muMatrix := by
      simp only [RingHom.toMonoidHom_eq_coe, MonoidHom.coe_coe, RingHom.mapMatrix_apply,
        ValuationSubring.coe_subtype]
      unfold muMatrixInt muMatrix
      ext i j
      fin_cases i
      · fin_cases j
        · simp
        simp only [Fin.zero_eta, Fin.isValue, Fin.mk_one, Matrix.map_apply, Matrix.of_apply,
          Matrix.cons_val', Matrix.cons_val_one, Matrix.cons_val_fin_one, Matrix.cons_val_zero,
          MulMemClass.coe_mul]
        rw[hq₁]
        ring_nf
        sorry -- algebra
      fin_cases j
      · simp
      simp
    rw[← m] at inteq

    constructor
    · -- image of unit
      sorry
    -- in localTameLevel
    sorry
  assumption


end CosetComputation

lemma U_mul {v : HeightOneSpectrum (𝓞 F)}
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0) :
    (U r S R α hα ∘ₗ U r S R β hβ) =
    U r S R (α * β) (hα.mul hβ) := by
  ext a
  rw[U, U, U]
  simp only [MulEquiv.toMonoidHom_eq_coe, LinearMap.coe_comp, Function.comp_apply,
    MulMemClass.coe_mul, mul_inv_rev]
  apply (Subtype.coe_inj).mp
  conv_rhs =>
    apply AbstractHeckeOperator.HeckeOperator_apply
  conv_lhs =>
    apply AbstractHeckeOperator.HeckeOperator_apply
  conv_lhs =>
    arg 1; ext; arg 1; ext; arg 2;
    apply AbstractHeckeOperator.HeckeOperator_apply
  #check U_coset α hα
  #check RestrictedProduct.mem_coset_and_mulSupport_subset_of_isProductAt

  sorry

lemma U_comm {v : HeightOneSpectrum (𝓞 F)}
    {α β : v.adicCompletionIntegers F} (hα : α ≠ 0) (hβ : β ≠ 0) :
    U r S R α hα ∘ₗ U r S R β hβ =
    U r S R β hβ ∘ₗ U r S R α hα := by
  rw [U_mul, U_mul]
  congr 1
  rw [mul_comm]

end HeckeOperator

open HeckeOperator

/-- `HeckeAlgebra F D r S R` is the Hecke algebra associated to the weight 2
`R`-valued automorphic forms associated to the discriminant 1 totally definite
quaternion algebra `D` over the totally real field `F`, of level `U₁(S)` where `S` is
a finite set of nonzero primes `v` of `𝓞 F`. To make sense of this definition we choose
a rigidification `r`, that is, a fixed `𝔸_F^∞`-linear
isomorphism `D ⊗[F] 𝔸_F^∞ = M₂(𝔸_F^∞)`, enabling us to define level structures and
Hecke operators `Tᵥ` and `Uᵥ` using 2x2 matrices.

Details: `U₁(S)` is the subgroup of `(D ⊗[F] 𝔸_F^∞)ˣ` associated, via `r`, to the
matrices which are in `GL₂(𝓞ᵥ)` for all `v ∉ S` and which are of the form
`(a *; 0 a)` mod `v` for all `v ∈ S`. The Hecke algebra is defined to be the
sub-`R`-algebra of the weight 2 forms of level `U₁(S)` generated by the following
two kinds of Hecke operators: first there are the operators
`Tᵥ` associated to the matrices `(ϖᵥ 0; 0 1)` for `v ∉ S` (here `ϖᵥ ∈ 𝔸_F^∞` is a local
uniformiser supported at `v`). Second, there are the Hecke operators `Uᵥ,ₐ`
for `v ∈ S` and `0 ≠ αᵥ ∈ 𝓞ᵥ`, associated the matries `(αᵥ 0; 0 1)`.
These slightly nonstandard Hecke operators satisfy `Uᵥ,ₛ * Uᵥ,ₜ = Uᵥ,ₛₜ`
and in particular this Hecke algebra is commutative (Hecke operators supported
at distinct primes commute because the decomposition of the double cosets
into single cosets can be done purely locally).
-/
def HeckeAlgebra : Type _ :=
  (Algebra.adjoin R ({T r R v | v ∉ S} ∪
  {φ | ∃ (v : HeightOneSpectrum (𝓞 F)) (_hv : v ∈ S)
         (α : v.adicCompletionIntegers F) (hα : α ≠ 0), φ = U r S R α hα}) :
    Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

namespace HeckeAlgebra

noncomputable instance instRing :
    Ring (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Ring (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

noncomputable instance instAlgebra :
    Algebra R (HeckeAlgebra F D r S R) := inferInstanceAs <|
  Algebra R (Algebra.adjoin R _ : Subalgebra R (WeightTwoAutomorphicFormOfLevel (U1 r S) R →ₗ[R]
      WeightTwoAutomorphicFormOfLevel (U1 r S) R))

noncomputable instance instCommRing :
    CommRing (HeckeAlgebra F D r S R) where
  __ := instRing F D r S R
  mul_comm := sorry -- #585 -- check on generators

variable {F S} in
/-- The Hecke operator Tᵥ as an element of the Hecke algebra. -/
noncomputable def T (v : HeightOneSpectrum (𝓞 F)) (hv : v ∉ S) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.T r R v, by
    apply Algebra.subset_adjoin
    left
    use v⟩



variable {F S} in
/-- The Hecke operator Uᵥ,ₐ as an element of the Hecke algebra. -/
noncomputable def U (v : HeightOneSpectrum (𝓞 F)) (hv : v ∈ S) (α : v.adicCompletionIntegers F)
    (hα : α ≠ 0) : HeckeAlgebra F D r S R :=
  ⟨HeckeOperator.U r S R α hα, by
    apply Algebra.subset_adjoin
    right
    use v, hv, α, hα⟩

end HeckeAlgebra

end TotallyDefiniteQuaternionAlgebra.WeightTwoAutomorphicForm
